apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: gcr.io/cloud-build-testbed/vote-app
    context: ./vote
    docker:
      dockerfile: Dockerfile
  - image: gcr.io/cloud-build-testbed/vote-result
    context: ./result
    docker:
      dockerfile: Dockerfile
  - image: gcr.io/cloud-build-testbed/vote-worker
    context: ./worker
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:    
    - postgres/deployment.yaml
    - redis/deployment.yaml
    - result/deployment.yaml
    - vote/deployment.yaml
    - worker/deployment.yaml