apiVersion: skaffold/v1beta8
kind: Config
build:
  artifacts:
  - image: gcr.io/cloud-build-testbed/vote-app
    context: ./vote
  - image: gcr.io/cloud-build-testbed/vote-result
    context: ./result
  - image: gcr.io/cloud-build-testbed/vote-worker
    context: ./worker
deploy:
  kubectl:
    manifests:    
    - postgres/deployment.yaml
    - redis/deployment.yaml
    - result/deployment.yaml
    - vote/deployment.yaml
    - worker/deployment.yaml

profiles:
  - name: cloud-build
    build:
      googleCloudBuild: {}